### ISSUE TITLE
[홈 화면] 설정 도중에 홈으로 돌아오는 경우 탭 바가 사라지는 버그

### ISSUE THREAD

**Issue by jeonyeohun** [boostcampwm-2021/iOS06-MateRunner#23]
## 🗣 설명
- 거리설정까지 갔다가 나오면 탭 바가 그대로 유지되는데, 모드 선택 화면에서 나오면 탭 바가 사라지는 버그가 있습니다. 아마 탭바 isHidden 처리에 예외 상황이 있는 것 같습니다.

https://user-images.githubusercontent.com/46087477/139873465-b896f03d-ea71-4fd9-a19b-88a782051a82.mp4

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트
- [x] 달리기 설정 중간 단계에서 홈 뷰컨트롤러로 나오더라도 탭 바가 사라지지 않고 보여야한다.

**Comment by devJungwonLee** [comment]
버그 해결했습니다.

**Comment by jeonyeohun** [comment]
> 버그 해결했습니다.

감사합니다!
