### ISSUE TITLE
[운동 전 타이머] 네비게이션바 숨김 처리와 폰트사이즈

### ISSUE THREAD

**Issue by lee-yujinn** [boostcampwm-2021/iOS06-MateRunner#33]
## 🗣 설명
- 이슈 내용 작성

<img  src="https://user-images.githubusercontent.com/41044154/140280511-abeaaafb-0a12-4c14-95fc-04d9d793b079.png"  width="40%"  height="40%">

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트
- [ ] 네비게이션 바 숨김처리 
- [ ] 폰트 사이즈 조금만 더 크게..

- [ ] 완료하지 못한 체크리스트
- [x] 완료한 체크리스트

**Comment by jeonyeohun** [comment]
https://github.com/boostcampwm-2021/iOS06-MateRunner/commit/fa93bdad8b0d4306997ea3fa1d685baf14763358 수정했습니다!
