### ISSUE TITLE
[칭찬 이모지 화면] CollectionView로 변경 및 ViewModel, UseCase 연결

### ISSUE THREAD

**Issue by lee-yujinn** [boostcampwm-2021/iOS06-MateRunner#90]
## 🗣 설명
- 친구 선택, 칭찬 이모지 화면에서 뷰컨의 input,output ViewModel, UseCase 연결

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

- [ ] 친구 선택 화면에서 뷰컨의 input,output ViewModel, UseCase 연결
- [ ] 칭찬 이모지 화면에서 뷰컨의 input,output ViewModel, UseCase 연결

**Comment by jeonyeohun** [comment]
이부분 화면 전환은 뷰컨에서 해두시면 제가 코디네이터에 연결하겠습니다! 뷰모델이랑 유즈케이스(runningsettng)는 외부에서 주입받는걸로 해주실 수 있나요?

https://github.com/boostcampwm-2021/iOS06-MateRunner/blob/e75f2b34e49492dcea861458e769c0ea063ad9b9/MateRunner/MateRunner/Presentation/HomeScene/ViewModel/DistanceSettingViewModel.swift#L14-L37

이런식으로요!

**Comment by lee-yujinn** [comment]
@jeonyeohun 넵 알겠습니다~ 근데 이모지 부분은 결과화면이 연결이 안되어있는것 같아서 따로 화면전환은 일단 안해두려고 해요!
