### ISSUE TITLE
[운동 중] 운동  완료 감지하여 결과 화면으로 넘어가도록 구현

### ISSUE THREAD

**Issue by mingd1023** [boostcampwm-2021/iOS06-MateRunner#97]
## 🗣 설명
- 운동  완료 감지하여 결과 화면으로 넘어가도록 구현

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 운동  완료 감지하여 결과 화면으로 넘어가도록 구현

**Comment by jeonyeohun** [comment]
1b95c34d84ab8f7cde243f1c8b2068e6534352c5 혼자 달리기 모드의 종료는 이 커밋에서 완료되었습니다. 같이 달리기 모드에서의 종료조건만 추가하면 될 것 같습니다.
